FROM oven/bun:alpine AS deps
WORKDIR /app

RUN apk add --no-cache postgresql-client curl

COPY package.json bun.lock ./
COPY packages/config/package.json ./packages/config/
COPY packages/schema/package.json ./packages/schema/
COPY nextjs/package.json ./nextjs/

RUN bun install

COPY packages ./packages
COPY nextjs ./nextjs

COPY .env.test .env.test


RUN \
  set -a && \
  source .env.test && \
  set +a && \
  NODE_OPTIONS="--max-old-space-size=4096" SKIP_ENV_VALIDATION=1 bun run build:test


EXPOSE 3000
