FROM oven/bun:alpine AS deps
WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY package.json bun.lock ./
COPY packages/config/package.json ./packages/config/
COPY packages/schema/package.json ./packages/schema/
COPY nextjs/package.json ./nextjs/

RUN bun install

COPY packages ./packages
COPY nextjs ./nextjs

# 後でリファクタ
RUN \
  export DATABASE_HOST=db && \
  export DATABASE_PORT=5432 && \
  export DATABASE_NAME=ptera_test && \
  export DATABASE_USER=postgres && \
  export DATABASE_PASSWORD=password && \
  export GOOGLE_CLIENT_ID=dummy-client-id && \
  export GOOGLE_CLIENT_SECRET=dummy-client-secret && \
  export JWT_SECRET=your-jwt-secret-key && \
  export NEXT_PUBLIC_DOMAIN_NAME='localhost:3000' && \
  export NEXT_PUBLIC_ENV=dev && \
  export NODE_ENV=production && \
  export NEXT_PUBLIC_TEST_BUILD=true && \
  NODE_OPTIONS="--max-old-space-size=4096" SKIP_ENV_VALIDATION=1 bun run build:test


EXPOSE 3000
