[tool.poetry]
name = "noveller"
version = "0.1.0"
description = ""
authors = ["Morio <xtarako@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
diagrams = "^0.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
