version: "3.8"
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ptera
      - REDIS_URL=redis://redis:6379
      - FRONTEND_PORT=3000
      - BACKEND_PORT=8000
    ports:
      - 3000:3000
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../backend/src/shared/infrastructure/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../backend/src/shared/infrastructure/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ptera
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  postgres-data:
  redis-data:
