version: "3.8"
services:
  # devcontainer:
  #   build:
  #     context: ..
  #     dockerfile: .devcontainer/Dockerfile
  #   volumes:
  #     - ..:/workspace:cached
  #   command: sleep infinity
  #   environment:
  #     - API_VERSION=v1
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/ptera
  #     - REDIS_URL=redis://redis:6379
  #     - BACKEND_URL=http://localhost:8000
  #     - FRONTEND_URL=http://localhost:3000
  #     - BACKEND_PORT=8000
  #   ports:
  #     - 3000:3000
  #     - 8000:8000
  #   depends_on:
  #     - db
  #     - redis
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ptera
    ports:
      - 5432:5432
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      ENGINE: PostgreSQLJDBC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RESOURCE_ARN: "arn:aws:rds:us-east-1:123456789012:cluster:dummy"
      SECRET_ARN: "arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy"
    ports:
      - "8080:80"
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  postgres-data:
  redis-data:
