name: "Deploy Application"

on:
  push:
    branches:
      - main
      - devel

permissions:
  id-token: write
  contents: read

jobs:
  filter:
    name: "Filter Changed Files"
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  validate:
    name: "Type Check"
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.frontend == 'true' || needs.filter.outputs.backend == 'true' }}

    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Use Cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            node-modules-

      # TODO: Turborepo など、モノレポツールの導入
      - name: Install Dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            bun install
            cd ..
          fi

          if [ -d "backend" ]; then
            cd backend
            bun install
            cd ..
          fi

      - name: Run Type Check
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            bun run typecheck || echo "Frontend type check failed"
            cd ..
          fi

          if [ -d "backend" ]; then
            cd backend
            bun run typecheck || echo "Backend type check failed"
            cd ..
          fi

  deploy-backend:
    name: "Deploy Backend"
    runs-on: ubuntu-latest
    needs: [filter, validate]
    if: ${{ needs.filter.outputs.backend == 'true' }}

    strategy:
      matrix:
        include:
          - branch: main
            environment: prod
            aws_role: "arn:aws:iam::ACCOUNT_ID:role/ptera-github-actions-prod"
          - branch: devel
            environment: dev
            aws_role: "arn:aws:iam::ACCOUNT_ID:role/ptera-github-actions-dev"

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ matrix.aws_role }}
          aws-region: ap-northeast-1

      # バックエンド（Lambda関数）をビルドしてデプロイ
      - name: Install Backend Dependencies
        run: |
          cd backend
          bun install --frozen-lockfile

      - name: Build Backend
        run: |
          cd backend
          bun run build

      - name: Package Lambda Function
        run: |
          cd backend
          bun run zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ptera-api-${{ matrix.environment }} \
            --zip-file fileb://backend/lambda.zip

  deploy-frontend:
    name: "Deploy Frontend"
    runs-on: ubuntu-latest
    needs: [filter, validate]
    if: ${{ needs.filter.outputs.frontend == 'true' }}

    strategy:
      matrix:
        include:
          - branch: main
            environment: prod
            aws_role: "arn:aws:iam::ACCOUNT_ID:role/ptera-github-actions-prod"
          - branch: devel
            environment: dev
            aws_role: "arn:aws:iam::ACCOUNT_ID:role/ptera-github-actions-dev"

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ matrix.aws_role }}
          aws-region: ap-northeast-1

      # フロントエンド（SPA）をビルドしてデプロイ
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          bun install --frozen-lockfile

      - name: Build Frontend
        run: |
          cd frontend
          VITE_API_URL=https:// ${{ matrix.environment == 'prod' && 'https://ptera.morio.space/api' || 'https://dev.ptera.morio.space/api' }} \
          bun run build

      # index.htmlは別々にデプロイ
      - name: Deploy Frontend to S3
        run: |
          aws s3 sync frontend/dist/ s3://ptera-spa-${{ matrix.environment }} \
            --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "index.html"
          aws s3 cp frontend/dist/index.html s3://ptera-spa-${{ matrix.environment }}/index.html \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
            --content-type "text/html; charset=utf-8"

      # CloudFrontのキャッシュを無効化
      # https://zenn.dev/keita_hino/articles/2a129d442daf05
      - name: Get CloudFront Distribution ID
        id: get-distribution-id
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Aliases.Items[?contains(@, '${{ matrix.environment == 'prod' && 'ptera.morio.space' || 'dev.ptera.morio.space' }}')]].Id" \
            --output text)
          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"
